// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminActions: typeof import('./src/components/AdminActions.vue')['default'];
    AvatarInput: typeof import('./src/components/userForm/AvatarInput.vue')['default'];
    ChapterCard: typeof import('./src/components/latestChapters/ChapterCard.vue')['default'];
    ChapterDelete: typeof import('./src/components/mangaChapters/ChapterDelete.vue')['default'];
    ChapterRow: typeof import('./src/components/mangaChapters/ChapterRow.vue')['default'];
    CommentBox: typeof import('./src/components/commentBox/CommentBox.vue')['default'];
    CommentCard: typeof import('./src/components/commentBox/CommentCard.vue')['default'];
    CommentCardActions: typeof import('./src/components/commentBox/CommentCardActions.vue')['default'];
    CommentEditInput: typeof import('./src/components/commentBox/CommentEditInput.vue')['default'];
    CommentInput: typeof import('./src/components/commentBox/CommentInput.vue')['default'];
    CommentList: typeof import('./src/components/commentBox/CommentList.vue')['default'];
    LatestChapters: typeof import('./src/components/latestChapters/LatestChapters.vue')['default'];
    LatestChaptersLoading: typeof import('./src/components/latestChapters/LatestChaptersLoading.vue')['default'];
    LatestManga: typeof import('./src/components/LatestManga.vue')['default'];
    LoadingCommentCard: typeof import('./src/components/commentBox/LoadingCommentCard.vue')['default'];
    LocalesItem: typeof import('./src/components/LocalesItem.vue')['default'];
    LoginForm: typeof import('./src/components/LoginForm.vue')['default'];
    MangaCard: typeof import('./src/components/mangaPage/MangaCard.vue')['default'];
    MangaChapters: typeof import('./src/components/mangaChapters/MangaChapters.vue')['default'];
    MangaChaptersLoading: typeof import('./src/components/mangaChapters/MangaChaptersLoading.vue')['default'];
    MangaFields: typeof import('./src/components/mangaForm/MangaFields.vue')['default'];
    MangaForm: typeof import('./src/components/mangaForm/MangaForm.vue')['default'];
    MangaPage: typeof import('./src/components/mangaPage/MangaPage.vue')['default'];
    MangaPageLoading: typeof import('./src/components/mangaPage/MangaPageLoading.vue')['default'];
    MangaRow: typeof import('./src/components/mangaRow/MangaRow.vue')['default'];
    MangaRowLoading: typeof import('./src/components/mangaRow/MangaRowLoading.vue')['default'];
    NavBar: typeof import('./src/components/NavBar.vue')['default'];
    Notifications: typeof import('./src/components/Notifications.vue')['default'];
    PagedReader: typeof import('./src/components/pagedReader/PagedReader.vue')['default'];
    PagedReaderDelimiterSlide: typeof import('./src/components/pagedReader/PagedReaderDelimiterSlide.vue')['default'];
    PagedReaderSlide: typeof import('./src/components/pagedReader/PagedReaderSlide.vue')['default'];
    PagedReaderTabs: typeof import('./src/components/pagedReader/PagedReaderTabs.vue')['default'];
    PageInput: typeof import('./src/components/uploadForm/pageInput/PageInput.vue')['default'];
    PageInputAddCard: typeof import('./src/components/uploadForm/pageInput/PageInputAddCard.vue')['default'];
    PageInputCard: typeof import('./src/components/uploadForm/pageInput/PageInputCard.vue')['default'];
    ReaderMenu: typeof import('./src/components/readerMenu/ReaderMenu.vue')['default'];
    ReaderMenuFab: typeof import('./src/components/readerMenu/ReaderMenuFab.vue')['default'];
    SearchBar: typeof import('./src/components/mangaPage/SearchBar.vue')['default'];
    SettingsForm: typeof import('./src/components/settingsForm/SettingsForm.vue')['default'];
    SettingsFormFields: typeof import('./src/components/settingsForm/SettingsFormFields.vue')['default'];
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default'];
    UploadForm: typeof import('./src/components/uploadForm/UploadForm.vue')['default'];
    UploadFormFields: typeof import('./src/components/uploadForm/UploadFormFields.vue')['default'];
    UserDeleteButton: typeof import('./src/components/userList/UserDeleteButton.vue')['default'];
    UserEditButton: typeof import('./src/components/userList/UserEditButton.vue')['default'];
    UserFilter: typeof import('./src/components/userList/UserFilter.vue')['default'];
    UserForm: typeof import('./src/components/userForm/UserForm.vue')['default'];
    UserFormFields: typeof import('./src/components/userForm/UserFormFields.vue')['default'];
    UserRow: typeof import('./src/components/userList/UserRow.vue')['default'];
    UserRowLoading: typeof import('./src/components/userList/UserRowLoading.vue')['default'];
    UsersList: typeof import('./src/components/userList/UsersList.vue')['default'];
    VAlert: typeof import('vuetify/lib')['VAlert'];
    ValidationObserver: typeof import('vee-validate')['ValidationObserver'];
    ValidationProvider: typeof import('vee-validate')['ValidationProvider'];
    VBtn: typeof import('vuetify/lib')['VBtn'];
    VCard: typeof import('vuetify/lib')['VCard'];
    VCardText: typeof import('vuetify/lib')['VCardText'];
    VCardTitle: typeof import('vuetify/lib')['VCardTitle'];
    VCheckbox: typeof import('vuetify/lib')['VCheckbox'];
    VCol: typeof import('vuetify/lib')['VCol'];
    VCombobox: typeof import('vuetify/lib')['VCombobox'];
    VDivider: typeof import('vuetify/lib')['VDivider'];
    VerticalReader: typeof import('./src/components/VerticalReader.vue')['default'];
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel'];
    VExpansionPanelContent: typeof import('vuetify/lib')['VExpansionPanelContent'];
    VExpansionPanelHeader: typeof import('vuetify/lib')['VExpansionPanelHeader'];
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels'];
    VForm: typeof import('vuetify/lib')['VForm'];
    VIcon: typeof import('vuetify/lib')['VIcon'];
    VRow: typeof import('vuetify/lib')['VRow'];
    VSelect: typeof import('vuetify/lib')['VSelect'];
    VTab: typeof import('vuetify/lib')['VTab'];
    VTabs: typeof import('vuetify/lib')['VTabs'];
    VTextarea: typeof import('vuetify/lib')['VTextarea'];
    VTextField: typeof import('vuetify/lib')['VTextField'];
  }
}

export {};
