version: '3.4'

services:
  webui:
    image: monochrome-webui-vue3
    build:
      context: .
      target: dev
      args:
        - PROTOCOL
        - DOMAIN_NAME
        - BASE_URL
        - TITLE
        - DESCRIPTION
        - VITE_API_PATH
        - VITE_MEDIA_PATH
    env_file:
      - .env
    volumes:
      - '.:/mnt'
    working_dir: /mnt
    ports:
      - 80:80
