name: Create and publish a Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NGINX: flashspys/nginx-static
  BASE_IMAGE_CADDY: 'caddy:2.4.5-alpine'
  BASE_IMAGE_PLATFORMS: 'linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release metadata
        id: get_release_metadata
        run: |
          release_tag=${{ steps.get_release.outputs.tag_name }}
          tag_regex='(v[0-9]+\.[0-9]+.[0-9]+).*'
          app_tag=$([[ $release_tag =~ $tag_regex ]] && echo "${BASH_REMATCH[1]}")
          release_version=$(echo $release_tag | cut -c2-)
          image_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=release_version::$release_version"
          echo "::set-output name=release_tag::$release_tag"
          echo "::set-output name=app_tag::$app_tag"
          echo "::set-output name=image_name::$image_name"
          release_commit=$(git rev-list --count HEAD)
          echo "::set-output name=release_commit::$release_commit"
          build_date=$(date "+%F")
          echo "::set-output name=build_date::$build_date"

      - name: Node.js setup
        id: node-setup
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install dependencies
        id: node-deps
        run: yarn

      - name: Build dist folder
        id: node-build
        run: yarn build
        env:
          DOMAIN_NAME: ${{ secrets.domain_name }}
          TITLE: ${{ secrets.app_title }}
          VITE_MEDIA_PATH: ${{ secrets.media_path }}
          VITE_API_PATH: ${{ secrets.api_path }}
          DESCRIPTION: ${{ secrets.app_description }}
          PROTOCOL: ${{ secrets.protocol }}
          BASE_URL: ${{ secrets.public_url }}
      - name: Build and push nginx release
        id: docker_build_release_nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/GHActions_Dockerfile
          platforms: ${{ env.BASE_IMAGE_PLATFORMS }}
          push: true
          target: nginx
          build-args: |
            BASE_IMAGE_NGINX=${{ env.BASE_IMAGE_NGINX }}
            BUILD_DATE=${{ steps.get_release_metadata.outputs.build_date }}
            IMAGE_VERSION=${{ steps.get_release_metadata.outputs.release_version }}
            GIT_COMMIT=${{ steps.get_release_metadata.outputs.release_commit }}
            RELEASE_TAG=${{ steps.get_release_metadata.outputs.release_tag }}
            APP_TAG=${{ steps.get_release_metadata.outputs.app_tag }}
          tags: |
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:nginx
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:${{ steps.get_release_metadata.outputs.release_tag }}-nginx
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:${{ steps.get_release_metadata.outputs.app_tag }}-nginx
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push caddy release
        id: docker_build_release_caddy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/GHActions_Dockerfile
          platforms: ${{ env.BASE_IMAGE_PLATFORMS }}
          push: true
          target: caddy
          build-args: |
            BASE_IMAGE_CADDY=${{ env.BASE_IMAGE_CADDY }}
            BUILD_DATE=${{ steps.get_release_metadata.outputs.build_date }}
            IMAGE_VERSION=${{ steps.get_release_metadata.outputs.release_version }}
            GIT_COMMIT=${{ steps.get_release_metadata.outputs.release_commit }}
            RELEASE_TAG=${{ steps.get_release_metadata.outputs.release_tag }}
            APP_TAG=${{ steps.get_release_metadata.outputs.app_tag }}
          tags: |
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:caddy
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:${{ steps.get_release_metadata.outputs.release_tag }}-caddy
            ghcr.io/${{ steps.get_release_metadata.outputs.image_name }}:${{ steps.get_release_metadata.outputs.app_tag }}-caddy
          cache-from: type=gha
          cache-to: type=gha,mode=max
